extension_dir = "C:\Program Files\php-8.5.1-nts-Win32-vs17-x64\ext"
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_mbstring.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_pdo_pgsql.dll
extension=php_pgsql.dll
extension=php_zip.dll
extension=php_gd.dll

error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
display_errors = Off
log_errors = On
max_execution_time = 120
default_socket_timeout = 30

; Fix SSL certificate verification for Firebase
curl.cainfo = "c:\PFE\recrutement\backend\cacert.pem"
openssl.cafile = "c:\PFE\recrutement\backend\cacert.pem"
