import logging
import asyncio
from typing import Dict, Any

from .state import MatchingState
from ..ingestion.ingestion_agent import IngestionAgent
from .llm_extractor import MatchingLLMExtractor

logger = logging.getLogger(__name__)

async def cv_parser_node(state: MatchingState) -> MatchingState:
    """Node 1 - ORCHESTRATION LAYER: CV Parsing (LLM Task)."""
    ingestion = IngestionAgent()
    cv_result = await ingestion.process_cv(state["cv_path"])
    
    extractor = MatchingLLMExtractor()
    cand_evidence = await extractor.extract_candidate_evidence(
        cv_result["profile"].get("raw_text", ""), cv_result["profile"]
    )
    
    cv_result["profile"]["evidence"] = cand_evidence
    
    return {
        "candidate_profile": cv_result["profile"],
        "candidate_embedding": cv_result["embedding"],
        "confidence_score": cv_result.get("confidence", 1.0),
        "audit_log": [f"CV Parsing complete. {len(cand_evidence)} evidence points extracted."]
    }

async def jd_understanding_node(state: MatchingState) -> MatchingState:
    """Node 2 - ORCHESTRATION LAYER: JD Understanding (LLM Task)."""
    ingestion = IngestionAgent()
    job_result = await ingestion.process_job(state["job_description"], state["job_requirements"])
    
    extractor = MatchingLLMExtractor()
    job_requirements = await extractor.extract_job_requirements(
        state["job_description"], job_result["profile"]
    )
    
    job_result["profile"]["requirements"] = job_requirements
    
    return {
        "job_profile": job_result["profile"],
        "job_embedding": job_result["embedding"],
        "audit_log": ["JD Understanding complete. Critical requirements identified."]
    }

async def explanation_node(state: MatchingState) -> MatchingState:
    """Node 3 - ORCHESTRATION LAYER: Reason Generation (LLM Task)."""
    # This node creates human-readable rationale based on pre-calculated scores
    status = state.get("gate_status", "REVIEW")
    final_score = state.get("final_score", 0.0)
    
    if status == "FAIL":
        explanation = f"Match rejected. Fundamental gaps identified in critical skill sets."
    else:
        explanation = f"Candidate is a {final_score*100:.0f}% match. Strengths align with core requirements."

    return {
        "explanation": explanation,
        "audit_log": ["Final rationale generated by LLM."]
    }
