# Generated by Django 5.2.12 on 2026-03-21 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField()),
                ('job_offer_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('hr_initiator_id', models.IntegerField()),
                ('num_questions', models.IntegerField(default=8)),
                ('difficulty_setting', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('review', 'Under Review'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('skills_covered', models.JSONField(blank=True, default=list)),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz_sessions',
            },
        ),
        migrations.CreateModel(
            name='SectionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('cluster_id', models.IntegerField()),
                ('meta_summary', models.TextField()),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('parent_chunk_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'section_summaries',
            },
        ),
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('uploader_id', models.IntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('minio_path', models.CharField(max_length=512)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('domain_tags', models.JSONField(blank=True, default=list)),
                ('seniority_scores', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_sections', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kb_documents',
                'indexes': [models.Index(fields=['company_id'], name='kb_document_company_910948_idx'), models.Index(fields=['status'], name='kb_document_status_8fc24f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('summary_quality_score', models.FloatField(blank=True, null=True)),
                ('summary_quality_flag', models.BooleanField(default=False)),
                ('domain', models.JSONField(blank=True, default=list)),
                ('seniority_junior', models.IntegerField(default=0)),
                ('seniority_mid', models.IntegerField(default=0)),
                ('seniority_senior', models.IntegerField(default=0)),
                ('source_filename', models.CharField(max_length=255)),
                ('estimated_page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_chunks', to='api.kbdocument')),
            ],
            options={
                'db_table': 'parent_chunks',
            },
        ),
        migrations.CreateModel(
            name='ChildChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='api.kbdocument')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='api.parentchunk')),
            ],
            options={
                'db_table': 'child_chunks',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('skill_targeted', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('reference_answer', models.TextField()),
                ('follow_up_hint', models.TextField(blank=True, null=True)),
                ('estimated_answer_length', models.IntegerField(default=200)),
                ('hyde_query', models.TextField(blank=True, null=True)),
                ('source_passage_indices', models.JSONField(default=list)),
                ('skill_embedding', models.BinaryField(blank=True, null=True)),
                ('is_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='api.quizquestion')),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('rouge_score', models.FloatField(default=0.0)),
                ('bert_score', models.FloatField(default=0.0)),
                ('cosine_score', models.FloatField(default=0.0)),
                ('llm_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('scoring_reasoning', models.TextField(blank=True, null=True)),
                ('missing_concepts', models.JSONField(default=list)),
                ('correct_concepts', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored')], default='pending', max_length=20)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_answers', to='api.quizquestion')),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizReport',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report', serialize=False, to='api.quizsession')),
                ('total_score_normalized', models.FloatField()),
                ('narrative_summary', models.TextField()),
                ('skill_breakdown', models.JSONField()),
                ('critical_gaps', models.JSONField()),
                ('confirmed_strengths', models.JSONField()),
                ('interview_suggestions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_reports',
            },
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['candidate_id', 'job_offer_id'], name='quiz_sessio_candida_198b95_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['company_id'], name='quiz_sessio_company_859a2a_idx'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quizsession'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizsession'),
        ),
        migrations.AddIndex(
            model_name='sectionsummary',
            index=models.Index(fields=['company_id'], name='section_sum_company_c9e042_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchunk',
            index=models.Index(fields=['company_id'], name='parent_chun_company_220181_idx'),
        ),
        migrations.AddIndex(
            model_name='childchunk',
            index=models.Index(fields=['company_id'], name='child_chunk_company_de2bf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('session', 'question_number')},
        ),
    ]
