# Generated by Django 5.2.12 on 2026-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizsession_job_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='hallucination_flag',
            field=models.BooleanField(default=False),
        ),
    ]
