# Generated by Django 5.2.12 on 2026-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quizquestion_mcq_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childchunk',
            name='content',
            field=models.TextField(db_column='content'),
        ),
        migrations.RenameField(
            model_name='childchunk',
            old_name='content',
            new_name='_content',
        ),
        migrations.AlterField(
            model_name='kbdocument',
            name='full_text',
            field=models.TextField(blank=True, db_column='full_text', null=True),
        ),
        migrations.RenameField(
            model_name='kbdocument',
            old_name='full_text',
            new_name='_full_text',
        ),
        migrations.AlterField(
            model_name='parentchunk',
            name='content',
            field=models.TextField(db_column='content'),
        ),
        migrations.RenameField(
            model_name='parentchunk',
            old_name='content',
            new_name='_content',
        ),
        migrations.AlterField(
            model_name='parentchunk',
            name='summary',
            field=models.TextField(blank=True, db_column='summary', null=True),
        ),
        migrations.RenameField(
            model_name='parentchunk',
            old_name='summary',
            new_name='_summary',
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answer_text',
            field=models.TextField(blank=True, db_column='answer_text', default=''),
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='answer_text',
            new_name='_answer_text',
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='scoring_reasoning',
            field=models.TextField(blank=True, db_column='scoring_reasoning', null=True),
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='scoring_reasoning',
            new_name='_scoring_reasoning',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='candidate_feedback',
            field=models.CharField(blank=True, choices=[('fausse', 'Fausse / Hors Sujet'), ('trop_facile', 'Trop facile'), ('trop_dure', 'Trop dure'), ('bonne', 'Bonne question')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kbdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
