# Generated by Django 5.2.12 on 2026-04-23 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_childchunk_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('parsed_profile', models.JSONField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_descriptions',
            },
        ),
        migrations.CreateModel(
            name='WeightBias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_bias', models.FloatField(default=0.0)),
                ('experience_bias', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weight_biases',
            },
        ),
        migrations.CreateModel(
            name='MatchingFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('decision', models.CharField(max_length=20)),
                ('scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matching_feedback',
                'indexes': [models.Index(fields=['candidate_id'], name='matching_fe_candida_a170a9_idx'), models.Index(fields=['job_id'], name='matching_fe_job_id_bca3ac_idx'), models.Index(fields=['decision'], name='matching_fe_decisio_60d53f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('candidate_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('result_data', models.JSONField()),
                ('is_stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_results',
                'indexes': [models.Index(fields=['job_id', 'candidate_id'], name='match_resul_job_id_896763_idx'), models.Index(fields=['is_stale'], name='match_resul_is_stal_6279a5_idx')],
                'unique_together': {('job_id', 'candidate_id')},
            },
        ),
    ]
